license_keys = {
    "AFL-1.1": "Academic Free License version 1.1",
    "AFL-1.2": "Academic Free License version 1.2",
    "AFL-2.0": "Academic Free License version 2.0",
    "AFL-2.1": "Academic Free License version 2.1",
    "AFL-3.0": "Academic Free License version 3.0",
    "AGPL-3.0/AGPL-3.0-only": "GNU Affero General Public License as published by the Free Software Foundation, version 3",
    "AGPL-3.0-or-later": "GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version",
    "Apache-2.0": "Apache License, Version 2.0",
    "APSL-2.0": "Apple Public Source License Version 2.0",
    "BitTorrent-1.0": "BitTorrent Open Source License Version 1.0",
    "BitTorrent-1.1": "BitTorrent Open Source License Version 1.1",
    "BUSL-1.1": "Business Source License",
    "CPAL-1.0": "Common Public Attribution License Version 1.0",
    "CUA-QPL-1.0": "CUA Office Public License Version 1.0",
    "ECL-1.0": "Educational Community License version 1.0",
    "ECL-2.0": "Educational Community License, Version 2.0",
    "EPL-1.0": "Eclipse Public License v1.0",
    "EPL-2.0": "Eclipse Public License v2.0",
    "GFDL-1.1": "GNU Free Documentation License, Version 1.1 or any later version published by the Free Software Foundation",
    "GFDL-1.1-invariants-only": "GNU Free Documentation License, Version 1.1; with the Invariant",
    "GFDL-1.1-invariants-or-later": "GNU Free Documentation License, Version 1.1 or any later version published by the Free Software Foundation; with the Invariant",
    "GFDL-1.1-no-invariants-only": "GNU Free Documentation License, Version 1.1; with no Invariant",
    "GFDL-1.1-no-invariants-or-later": "GNU Free Documentation License, Version 1.1 or any later version published by the Free Software Foundation; with no Invariant",
    "GFDL-1.1-only": "GNU Free Documentation License, Version 1.1; with the Invariant",
    "GFDL-1.1-or-later": "GNU Free Documentation License, Version 1.1 or any later version published by the Free Software Foundation; with the Invariant",
    "GFDL-1.2": "GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation",
    "GFDL-1.2-invariants-only": "GNU Free Documentation License, Version 1.2; with the Invariant",
    "GFDL-1.2-invariants-or-later": "GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with the Invariant",
    "GFDL-1.2-no-invariants-only": "GNU Free Documentation License, Version 1.2; with no Invariant",
    "GFDL-1.2-no-invariants-or-later": "GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with no Invariant",
    "GFDL-1.2-only": "GNU Free Documentation License, Version 1.2; with the Invariant",
    "GFDL-1.2-or-later": "GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with the Invariant",
    "GFDL-1.3": "GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation",
    "GFDL-1.3-invariants-only": "GNU Free Documentation License, Version 1.3; with with the Invariant",
    "GFDL-1.3-invariants-only-fixed": "GNU Free Documentation License, Version 1.3; with the Invariant",
    "GFDL-1.3-invariants-or-later": "GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with the Invariant",
    "GFDL-1.3-no-invariants-only": "GNU Free Documentation License, Version 1.3; with no Invariant",
    "GFDL-1.3-no-invariants-or-later": "GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with no Invariant",
    "GFDL-1.3-only": "GNU Free Documentation License, Version 1.3; with the Invariant",
    "GFDL-1.3-or-later": "GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with the Invariant",
    "GPL-1.0-or-later/GPL-1.0+": "GNU General Public License as published by the Free Software Foundation; either version 1, or (at your option) any later version",
    "GPL-1.0/GPL-1.0-only": "GNU General Public License as published by the Free Software Foundation; version 1",
    "GPL-2.0-or-later/GPL-2.0+": "GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version",
    "GPL-2.0/GPL-2.0-only": "GNU General Public License as published by the Free Software Foundation; version 2",
    "GPL-3.0-or-later/GPL-3.0+": "GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version",
    "GPL-3.0/GPL-3.0-only": "GNU General Public License as published by the Free Software Foundation, version 3",
    "Interbase-1.0": "Interbase Public License Version 1.0",
    "LGPL-2.0-or-later/LGPL-2.0+": "GNU Library General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version",
    "LGPL-2.0/LGPL-2.0-only": "GNU Library General Public License as published by the Free Software Foundation; version 2",
    "LGPL-2.1-or-later/LGPL-2.1+": "GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version",
    "LGPL-2.1/LGPL-2.1-only": "GNU Lesser General Public License as published by the Free Software Foundation; version 2.1",
    "LPPL-1.0": "LaTeX Project Public License Distributed from CTAN",
    "LPPL-1.1": "LaTeX Project Public License, either version 1.1",
    "LPPL-1.2": "LaTeX Project Public License, either version 1.2",
    "LPPL-1.3": "LaTeX Project Public License, either version 1.3",
    "MPL-1.0": "Mozilla Public License Version 1.0",
    "MPL-1.1": "Mozilla Public License Version 1.1",
    "MPL-2.0": "Mozilla Public License, v. 2.0",
    "MPL-2.0-no-copyleft-exception": "This Source Code Form is \"Incompatible With Secondary Licenses\", as defined by the Mozilla Public License, v. 2.0",
    "MulanPSL-1.0": "licensed under the Mulan PSL v1",
    "MulanPSL-2.0": "licensed under Mulan PSL v2",
    "OCLC-2.0": "OCLC Research Public License Version 2.0",
    "OSL-1.0": "Open Software License version 1.0",
    "OSL-1.1": "Open Software License version 1.1",
    "OSL-2.0": "Open Software License version 2.0",
    "OSL-2.1": "Open Software License version 2.1",
    "OSL-3.0": "Open Software License version 3.0",
    "Pixar": "Licensed under the Apache License, Version 2.0 (the \"Apache License\") with the following modification",
    "RPSL-1.0": "Public Source License Version 1.0",
    "SCEA": "SCEA Shared Source License, Version 1.0",
    "SGI-B-1.0": "SGI Free Software License B, Version 1.0",
    "SGI-B-1.1": "SGI Free Software License B, Version 1.1",
    "SHL-0.5": "Solderpad Hardware License, Version 0.5",
    "SHL-0.51": "Solderpad Hardware License, Version 0.51",
    "SISSL": "Sun Standards License Version 1.1",
    "SISSL-1.2": "Sun Industry Standards Source License Version 1.2",
    "SPL-1.0": "Sun Public License Version 1.0",
    "SSPL-1.0": "Server Side Public License, version 1",
    "TGPPL-1.0": "Transitive Grace Period Public Licence version 1.0",
    "TPL-1.0": "THOR Public License Version 1.0",
    "UCL-1.0": "Upstream Compatibility License 1.0",
    "W3C": "W3C® Software License",
    "W3C-20150513": "W3C® Software License [1]"
}

dual_license_keys = {
    "Eclipse-1.0/LGPL-2.1": ["Eclipse Public License v1.0", "GNU Lesser General Public License version 2.1"]
}

multi_license_keys = {
    "GPL-2.0-with-autoconf-exception": ["GNU General Public License v2.0 w/Autoconf exception", "GPL-2.0-with-autoconf-exception"],
    "GPL-2.0-with-bison-exception": ["GNU General Public License v2.0 w/Bison exception", "GPL-2.0-with-bison-exception"],
    "GPL-2.0-with-classpath-exception": ["GNU General Public License v2.0 w/Classpath exception", "GPL-2.0-with-classpath-exception"],
    "GPL-2.0-with-font-exception": ["GNU General Public License v2.0 w/Font exception", "GPL-2.0-with-font-exception"],
    "GPL-2.0-with-GCC-exception": ["GNU General Public License v2.0 w/GCC Runtime Library exception", "GPL-2.0-with-GCC-exception"],
    "GPL-3.0-with-autoconf-exception": ["GNU General Public License v3.0 w/Autoconf exception", "GPL-3.0-with-autoconf-exception"],
    "GPL-3.0-with-GCC-exception": ["GNU General Public License v3.0 w/GCC Runtime Library exception", "GPL-3.0-with-GCC-exception"]
}

multi_license_inclusive_keys = {
    "GPL-2.0-with-autoconf-exception": ["GNU General Public License", "version 2", "Autoconf", "Exception"],
    "GPL-2.0-with-bison-exception": ["GNU General Public License", "version 2", "Bison", "Exception"],
    "GPL-2.0-with-classpath-exception": ["GNU General Public License", "version 2", "Classpath", "Exception"],
    "GPL-2.0-with-font-exception": ["GNU General Public License", "version 2", "Font", "Exception"],
    "GPL-2.0-with-GCC-exception": ["GNU General Public License", "version 2", "GCC", "Exception"],
    "GPL-3.0-with-autoconf-exception": ["GNU General Public License", "version 3", "Autoconf", "Exception"],
    "GPL-3.0-with-GCC-exception": ["GNU General Public License", "version 3", "GCC", "Exception"]
}

other_license_keys = {
    "VINAY SAJIP": "VINAY SAJIP DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE",
    "Portions (C) International Organization for Standardization": "Portions (C) International Organization for Standardization"
}